name = "Architectury API (Fabric)"
filename = "architectury-1.17.22-fabric.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3351/378/architectury-1.17.22-fabric.jar"
hash-format = "murmur2"
hash = "3555596237"

[update]
[update.curseforge]
file-id = 3351378
project-id = 419697
