name = "Conjuring [Fabric/Forge]"
filename = "conjuring-0.2.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3329/635/conjuring-0.2.3.jar"
hash-format = "murmur2"
hash = "2422155125"

[update]
[update.curseforge]
file-id = 3329635
project-id = 422310
