name = "Mouse Wheelie (Fabric)"
filename = "mousewheelie-1.7.3+mc1.16.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3340/662/mousewheelie-1.7.3+mc1.16.5.jar"
hash-format = "murmur2"
hash = "3559232823"

[update]
[update.curseforge]
file-id = 3340662
project-id = 317514
