name = "Reborn Core"
filename = "RebornCore-1.16-4.7.3+build.136.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3330/311/RebornCore-1.16-4.7.3+build.136.jar"
hash-format = "murmur2"
hash = "538529519"

[update]
[update.curseforge]
file-id = 3330311
project-id = 237903
