name = "Tech Reborn"
filename = "TechReborn-1.16-3.8.4+build.236.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3330/317/TechReborn-1.16-3.8.4+build.236.jar"
hash-format = "murmur2"
hash = "1339050301"

[update]
[update.curseforge]
file-id = 3330317
project-id = 233564
